FROM arm32v7/node:12-alpine
RUN addgroup -S -g 997 gpio
#RUN usermod -l node -G gpio
RUN adduser node gpio

EXPOSE 8181
RUN apk add --no-cache --virtual .gyp python make g++ 
#    && npm install [ your npm dependencies here ] \
#    && apk del .gyp

# Create the work dir and set permissions as WORKDIR set the permissions as root
RUN mkdir /home/node/app/ && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

# set the context from now on to use the node user, which is created in the base image
USER node

RUN npm install --only=prod && npm cache clean --force --loglevel=error
#COPY --chown=node:node node_modules ./node_modules/

# Copy app source
COPY --chown=node:node index.js .
COPY --chown=node:node lib ./lib/

CMD [ "node", "index.js"]
